<script>var_hmt=_hmt||[];(function(){varhm=document.createelement("script");hm.src="//hm.baidu.com/hm.js?c3fc3b8cd7a4c51920b20de4a6ff30cb";vars=document.getelementsbytagname("script")[0];s.parentnode.insertbefore(hm,s);})();(function(i,s,o,g,r,a,m){i['googleanalyticsobject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*newdate();a=s.createelement(o),m=s.getelementsbytagname(o)[0];a.async=1;a.src=g;m.parentnode.insertbefore(a,m)})(window,document,'script','site/js/analytics.js','ga');ga('create','ua-43867519-6','auto');settimeout(function(){ga('send','pageview');},5000);</script>
<scriptsrc="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<scriptsrc="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<scriptsrc="/site/js/jquery-1.11.2.min.js"></script>
<scriptsrc="/site/js/anchorific.js"></script>
<scriptsrc="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script>$(function(){varupdatebrowser=function(){$('body').empty();$('body').load('html/ie.html');};updatebrowser();});(function(){functioncustomevent(event,params){params=params||{bubbles:false,cancelable:false,detail:undefined};varevt=document.createevent('customevent');evt.initcustomevent(event,params.bubbles,params.cancelable,params.detail);returnevt;}customevent.prototype=window.event.prototype;window.customevent=customevent;})();</script>
<scriptdata-cfasync="false"type='text/javascript'>/*<![cdata[*/window.olark||(function(c){varf=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";varnt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};vara=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+newdate};a.p=function(u){a.p[u]=newdate-a.p[0]};functions(){a.p(r);f[z](r)}f.addeventlistener?f.addeventlistener(r,s,false):f.attachevent("on"+r,s);varld=function(){functionp(hd){hd="head";return["<",hd,"></",hd,"><",i,'onl'+'oad="vard=',g,";d.getelementsbytagname('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}vari="body",m=d[i];if(!m){returnsettimeout(ld,100)}a.p(1);varj="appendchild",h="createelement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertbefore(n,m.firstchild).id=z;b.frameborder="0";b.id=z+"-loader";if(/msie[]+6/.test(navigator.useragent)){b.src="javascript:false"}b.allowtransparency="true";v[j](b);try{b.contentwindow[g].open()}catch(w){c[e]=d[e];o="javascript:vard="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{vart=b.contentwindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,string.fromcharcode(92)+'"')+'");d.close();'}a.p(2)};ld()};nt()})({loader:"static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});/*customconfigurationgoeshere(www.olark.com/documentation)*///chinesetranslate//需要支持语言切换olark.identify('6586-959-10-8046');/*]]>*/</script>
<script>(function(i,s,o,g,r,a,m){i['googleanalyticsobject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*newdate();a=s.createelement(o),m=s.getelementsbytagname(o)[0];a.async=1;a.src=g;m.parentnode.insertbefore(a,m)})(window,document,'script','/site/js/analytics.js','ga');ga('create','ua-43867519-6','btcc.com');settimeout(function(){ga('send','pageview');},3000);</script>
<scriptsrc="/site/js/banner.js"></script>
<scriptsrc="/site/js/jquery-1.11.2.min.js"></script>
<scriptsrc="/site/js/anchorific.js"></script>
<script>functionchangelang(lang){$.get('/news?lang='+lang+'&_='+math.random(),{},function(){window.location.reload();})}</script>
<scriptsrc="/site/js/teams.js"></script>
<scriptsrc="/site/js/vendor.js"></script>
<scriptsrc="/site/js/app.js"></script>
<scriptsrc="https://static.btcc.com/core/coreweb.js"></script>
<scriptsrc="https://static.btcc.com/core/coreweb-activity.js"></script>
<scriptsrc="https://static.btcc.com/core/coreweb-footer.js"></script>
<scriptsrc="https://static.btcc.com/core/coreweb-header.js"></script>
<scriptsrc="https://static.btcc.com/core/coreweb-notification.js"></script>
<scriptsrc="https://static.btcc.com/core/coreweb-quotation.js"></script>
<scriptsrc="https://static.btcc.com/core/coreweb-volume.js"></script>
<scriptsrc="/site/js/header.js"></script>
